# Generated by Django 2.1.5 on 2022-05-25 12:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220522_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[app.models.validate_vehicle_no]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
